### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by joe-smalley** [francoiscote/acf-field-instagram#2]
I've just installed this plugin but get this error when I try to save a post with this new field type added:

Fatal error: Uncaught exception 'Exception' with message '::' in /wp-content/plugins/acf-field-instagram-master/acf-instagram-v5.php on line 417

**Comment by francoiscote** [comment]
I just merge a PR that should help, and also fixed a typo in the Exception throw. Update and let me know.
